# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cd52d7ac6fffd344a978729434ef7911bf99862b62cd86733daf404350d9016d899eead8025b1ac4dd09b31daeff4b709cb3bb6461abe41b559626547b4cc18

test:
  secret_key_base: 16e530245a9eb40b2cdc361aa0ca751727b76fb741acbadde0eaa26ebbe8ee0c4dd9de56a721c333d3045ff6add845e74192f611cf86b9277a92e5b26fe683aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
